Update travis config for LLVM-3.8

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,26 +1,67 @@
-language: haskell
-env:
- - GHCVER=7.6.3 CABALVER=1.18
- - GHCVER=7.8.3 CABALVER=1.18
- - GHCVER=7.10.1 CABALVER=1.22
+# This file has been generated by `make_travis_yml_2.hs`
+# see https://github.com/hvr/multi-ghc-travis for more information
+language: c
+sudo: false
+
+cache:
+  directories:
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
+
+matrix:
+  include:
+    - env: CABALVER=1.24 GHCVER=7.8.4
+      compiler: ": #GHC 7.8.4"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-7.8.4,llvm-3.8-dev,gcc-5,g++-5], sources: [hvr-ghc,llvm-toolchain-precise-3.8,ubuntu-toolchain-r-test]}}
+    - env: CABALVER=1.24 GHCVER=7.10.3
+      compiler: ": #GHC 7.10.3"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,llvm-3.8-dev,gcc-5,g++-5], sources: [hvr-ghc,llvm-toolchain-precise-3.8,ubuntu-toolchain-r-test]}}
+    - env: CABALVER=1.24 GHCVER=8.0.1
+      compiler: ": #GHC 8.0.1"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1,llvm-3.8-dev,gcc-5,g++-5], sources: [hvr-ghc,llvm-toolchain-precise-3.8,ubuntu-toolchain-r-test]}}
+
 before_install:
- - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
- - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
- - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- - sudo apt-get update
- - sudo apt-get install gcc-4.8 g++-4.8
- - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
- - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
- - sudo apt-get install libedit-dev llvm-3.5-dev
- - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
- - travis_retry sudo apt-get update
- - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
- - cabal --version
- - sudo /opt/ghc/$GHCVER/bin/ghc-pkg recache
- - /opt/ghc/$GHCVER/bin/ghc-pkg recache --user
- - cabal update
+ - mkdir -p /home/travis/bin
+ - ln -s /usr/bin/gcc-5 /home/travis/bin/gcc
+ - ln -s /usr/bin/g++-5 /home/travis/bin/g++
+ - ln -s /usr/bin/llvm-config-3.8 /home/travis/bin/llvm-config
+ - export PATH=/home/travis/bin:$PATH
+ - export CC=/usr/bin/gcc-5
+ - export CXX=/usr/bin/g++-5
+
 install:
-  - cabal install --only-dependencies --enable-tests --force-reinstall llvm-general-pure/ llvm-general/
+ - llvm-config --version
+ - gcc --version
+ - g++ --version
+ - cabal --version
+ - BENCH=${BENCH---enable-benchmarks}
+ - TEST=${TEST---enable-tests}
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
+   then
+     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
+          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
+   fi
+ - travis_retry cabal update -v
+ - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - cabal new-build ${TEST} ${BENCH} --dep
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
-  - cabal install --enable-tests llvm-general-pure/ llvm-general/
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ # this builds all libraries and executables (including tests/benchmarks)
+ - cabal new-build llvm-general-pure llvm-general --ghc-options '-pgmc gcc-5' ${TEST} ${BENCH} # -v2 provides useful information for debugging
+
+ # there's no 'cabal new-test' yet, so let's emulate for now
+ - TESTS=("llvm-general-pure-3.8.0.0/build/test/test" "llvm-general-3.8.0.0/build/test/test");
+   RC=true; for T in ${TESTS[@]}; do echo "== $T ==";
+   if dist-newstyle/build/$T; then echo "= $T OK =";
+   else echo "= $T FAILED ="; RC=false; fi; done; $RC
+
+# EOF
